spring:
  profiles:
    active: dev
  application:
    # 服务端创建的项目 id 需要与 application.name 保持一致
    name: dynamic-threadpool-example-hagsyn
  dynamic:
    thread-pool:
      # 服务端地址
      server-addr: http://localhost:6691
      # 用户名
      username: admin
      # 密码
      password: 123456
      # 租户 id, 对应 tenant 表
      namespace: hagsyn
      # 项目 id, 对应 item 表
      item-id: ${spring.application.name}

server:
  port: 8080

hagsyn:
  server:
    enabled: true
    user:
      aaa:
        name : 111
        age: 1
      bbb:
        name : 222
        age : 2